CREATE TABLE employee_profiles
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email   VARCHAR(255),
    address VARCHAR(255),
    CONSTRAINT pk_employee_profiles PRIMARY KEY (id)
);

CREATE TABLE employees
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(255),
    employee_profile_id BIGINT,
    CONSTRAINT pk_employees PRIMARY KEY (id)
);

ALTER TABLE employees
    ADD CONSTRAINT FK_EMPLOYEES_ON_EMPLOYEE_PROFILE FOREIGN KEY (employee_profile_id) REFERENCES employee_profiles (id);